### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by alex289** [alex289/Portfolio#7]
- [x] Change font
- [x] Reorder locales
- [x] Rename/Relocate components
- [x] Improve Lighthouse score
- [x] Add new Checkly checks
- [x] Make budget higher
- [x] Show info about logged in account
- [x] Improve dashboard
- [x] Translate blog posts
- [x] Add Terminal blog post
- [x] Show active page on navbar
- [x] improve design
- [x] Update social images of website
- [x] Update e2e tests
- [x] Add Date to blog
- [x] Add tags to Blog
- [x] Add about page
- [x] Add projects page
- [x] Move blog to a cms (Sanity)
- [x] Deploy sanity studio

Not going to add:
- [x] Maybe add confetti to guestbook
- [x] Add https://read.cv/explore
- [x] Maybe add Preact again

**Comment by XahidEx** [comment]
I've just looked at your Repo. Checked the beta app directory. Why not use Sanity anymore?

**Comment by alex289** [comment]
@XahidEx I'm working on moving to the app directory on the feature/app_directory branch. I like Sanity a lot but for me it's easier managing the blog posts with contentlayer.
